**********************************************************
**Derivar a partir de centroides ancla y etiquetar puntos*
**********************************************************
cd "$dataset"
use "xydatabase.dta", clear

gen x_anchor = int(x_c)
gen y_anchor = int(y_c)
gen x_label = x_anchor
gen y_label = y_anchor
sort AMBITO
dataex _ID AMBITO x_anchor y_anchor x_label y_label

* Example generated by -dataex-. To install: ssc install dataex
clear
input float _ID str20 AMBITO float(x_anchor y_anchor x_label y_label)
  1 "AMAZONAS"      -341  -561 -341  -561
  2 "ANCASH"        -298 -1044 -298 -1044
  3 "APURIMAC"       224 -1567  224 -1567
  4 "AREQUIPA"       279 -1774  279 -1774
  5 "AYACUCHO"       100 -1573  100 -1573
  6 "CAJAMARCA"     -418  -712 -418  -712
  7 "CALLAO"        -237 -1330 -237 -1330
  8 "CUSCO"          314 -1471  314 -1471
  9 "HUANCAVELICA"    -1 -1452   -1 -1452
 10 "HUANUCO"       -115 -1045 -115 -1045
 11 "ICA"            -64 -1590  -64 -1590
 12 "JUNIN"           12 -1284   12 -1284
 13 "LA LIBERTAD"   -376  -878 -376  -878
 14 "LAMBAYEQUE"    -538  -660 -538  -660
129 "LIMA"          -260 -1390 -260 -1390
 16 "LORETO"          62  -455   62  -455
 17 "MADRE DE DIOS"  495 -1334  495 -1334
 18 "MOQUEGUA"       462 -1892  462 -1892
 19 "PASCO"          -34 -1156  -34 -1156
 20 "PIURA"         -595  -567 -595  -567
 21 "PUNO"           560 -1600  560 -1600
130 "REGION LIMA"    -240 -1212 -240 -1212
 22 "SAN MARTIN"    -192  -779 -192  -779
 23 "TACNA"          524 -1983  524 -1983
 24 "TUMBES"        -618  -426 -618  -426
 25 "UCAYALI"        173 -1068  173 -1068
end

*Lima       -280 -1390 -280 -1390
*lambayeque -538  -660 -538  -660
*region lima -240 -1212 -240 -1212

****RECODIFICAR CALLAO, TUMBES

*Callao 
replace y_anchor=y_anchor if AMBITO=="CALLAO"
replace x_anchor=x_anchor - 200 if AMBITO=="CALLAO"

replace y_label=y_label if AMBITO=="CALLAO"
replace x_label=x_label - 200 if AMBITO=="CALLAO"

*Tumbes
replace y_anchor=y_anchor + 100 if AMBITO=="TUMBES"
replace x_anchor=x_anchor + 100 if AMBITO=="TUMBES"

replace y_label=y_label + 100 if AMBITO=="TUMBES"
replace x_label=x_label + 100 if AMBITO=="TUMBES"

gen rconnect = 1 if inlist(AMBITO,"CALLAO") 
/*si es callao rconnect==1, de lo contrario, 
toma el valor de missing*/
replace rconnect = 0 if inlist(AMBITO,"TUMBES") /*si es tumbes rconnect==0, de lo contrario, toma el valor de missing*/


* crear dos etiquetas para cada AMBITO
merge 1:1 AMBITO using "atributo.dta", assert(match) nogen
expand 2  /*duplicar observaciones*/
bysort AMBITO: gen lgroup = _n
*br AMBITO lgroup
*br AMBITO lgroup rconnect spc 
gen str20 s = cond(mi(rconnect), AMBITO, AMBITO + ", " + spc) if lgroup == 1
replace s = spc if mi(rconnect) & lgroup == 2
save "xy_dbase_ubicaciones.dta", replace