
*********************************************
****LINEAS QUE CONECTAN A LOS CUADRADOS 
*********************************************
* obtener la ubicación ancla del departamento
use "xy_dbase_ubicaciones.dta", clear
keep if !mi(rconnect)
keep if lgroup == 1
sort NOMBDEP
keep _ID NOMBDEP x_anchor y_anchor rconnect
list , sepby(rconnect)
tempfile anchors
save "`anchors'"

* cada polilínea contiene al menos 3 obs, comenzando con un valor faltante
* la segunda observación consta de la ubicación del punto de conexión cuadrado
use _ID NOMBDEP x_sq y_sq obs if obs <= 3 using "squares.dta", clear
merge m:1 NOMBDEP using "`anchors'", assert(match) nogen
isid NOMBDEP obs, sort

* move the label location as the final point in the polyline
gen _X = cond(obs == 3, x_anchor, x_sq)
gen _Y = cond(obs == 3, y_anchor, y_sq)

* imprima los datos iniciales de la polilínea, copie la salida aquí y ajuste según sea necesario
dataex _ID NOMBDEP _X _Y

* Example generated by -dataex-. To install: ssc install dataex
clear
input byte _ID str3 NOMBDEP float(_X _Y)
 7 "CALLAO"    .     .
 7 "CALLAO" -330 -1330
 7 "CALLAO" -245 -1330
24 "TUMBES"     .     .
24 "TUMBES"  -648  -326
24 "TUMBES"  -618  -426
end
drop NOMBDEP
save "connectors.dta", replace

gen lgroup2=1 
append using xy_coor_with_squares.dta
replace lgroup2=0 if lgroup2==.
save connectors2.dta,replace 